variable "name_prefix" {
  description = "Arbitrary string to prefix the output value with. No need for trailing dash, that will be added by the module."
  type        = "string"
}

variable "resource_type" {
  description = "AWS Resource type that the name will be generated by this module."
  type        = "string"
}
